version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/erictel
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key-here
      - JWT_EXPIRES_IN=7d
      - COINPAPRIKA_API_URL=https://api.coinpaprika.com/v1
      - PORT=3000
      - MAX_FILE_SIZE=5242880
      - UPLOAD_DEST=./uploads
    volumes:
      - ./uploads:/app/uploads
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - erictel-network
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=erictel
    volumes:
      - mongo_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - erictel-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - erictel-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - erictel-network
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:

networks:
  erictel-network:
    driver: bridge
